In [1]:
print('hello')

hello


# Numpy - Array Creation and use

In [2]:
import numpy as np

In [5]:
a = np.arange(4.0)
b = a * 23.4
c = b/(a+1)
c += 10
print(c)

[10.   21.7  25.6  27.55]


In [6]:
arr = np.arange(100, 200)
select = [5, 25,50, 75, -5]
print(arr[select])

[105 125 150 175 195]


In [8]:
arr = np.arange(10, 20)
div_by_3 = arr%3 == 0
print(div_by_3)

[False False  True False False  True False False  True False]


In [9]:
print(arr[div_by_3])

[12 15 18]


In [11]:
arr = np.arange(10, 20).reshape((2,5))
print(arr)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [12]:
arr.sum()

145

In [13]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
arr.mean()

14.5

In [15]:
arr.std()

2.8722813232690143

In [16]:
arr.max()

19

In [17]:
arr.min()

10

In [18]:
div_by_3.all()

False

In [19]:
div_by_3.any()

True

In [20]:
div_by_3.sum()

3

In [21]:
div_by_3.nonzero()

(array([2, 5, 8], dtype=int64),)

In [23]:
arr = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
arr.sort()
print(arr)

[1.2 1.8 2.3 4.5 5.5 6.7]


In [24]:
x = np.array([4.5, 2.3, 6.7, 1.2, 1.8, 5.5])
np.sort(x)

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [25]:
print(x)

[4.5 2.3 6.7 1.2 1.8 5.5]


In [26]:
s = x.argsort()
s

array([3, 4, 1, 0, 5, 2], dtype=int64)

In [28]:
x[s]

array([1.2, 1.8, 2.3, 4.5, 5.5, 6.7])

In [33]:
y = x * 2
y[s]

array([ 2.4,  3.6,  4.6,  9. , 11. , 13.4])

In [36]:
a = np.array([[1.0, 2.0], [4.0,3.0]])
a

array([[1., 2.],
       [4., 3.]])

In [37]:
a.transpose()

array([[1., 4.],
       [2., 3.]])

In [47]:
inv(a)

NameError: name 'inv' is not defined

In [43]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [49]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [50]:
np.dot(j,j)

array([[-1.,  0.],
       [ 0., -1.]])

In [52]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
a

array([1., 4., 3., 8., 9., 2., 3.])

In [53]:
np.median(a)

3.0

In [55]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [56]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])